// Css
import "./globals.css"
// Fonts
import { fontManrope, fontMono, fontSans } from "./fonts"
// Components
import { Footer, Header, Popup } from "@/components"
// Meta Data
export const metadata = {
  title: "Manhattan Book Marketing",
  description: "Generated by Manhattan Book Marketing",
  robots: {
  index: true,
  follow: true,
  googleBot: {
    index: true,
    follow: true,
    noimageindex: false,
    "max-video-preview": "large",
    "max-image-preview": "large",
    "max-snippet": -1,
    },
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} ${fontManrope.variable} antialiased font-sans font-normal text-black scroll-smooth`}
      >
        <Header />
        <main>
          {children}
        </main>
        <Footer />
        {/* <Popup /> */}
      </body>
    </html>
  );
}
